**Teknik Manual**

In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/nilai.csv', sep=',')
data.head(9)

  nim;nm_mhs;kelas;kd_mtk;nm_mtk;nilai tugas;keterangan
0      21042019;Rina;11.3B.05;255;DATA WAREHOUSE;95;
1       21042020;Uni;11.3B.05;255;DATA WAREHOUSE;90;
2      21042021;Diah;11.3B.05;255;DATA WAREHOUSE;85;
3     21042022;Ilham;11.3B.05;255;DATA WAREHOUSE;95;
4    21042023;Irwan;11.3B.05;255;DATA WAREHOUSE;100;
5     21042024;Ragil;11.3B.05;255;DATA WAREHOUSE;70;
6     21042025;Andre;11.3B.05;255;DATA WAREHOUSE;80;
7  21042026;Muhammad;11.3B.05;255;DATA WAREHOUSE;75;
8     21042027;Affan;11.3B.05;255;DATA WAREHOUSE;85;

In [ ]:
batas_bin = [0, 75, 85, 100]

In [ ]:
kategori = ['Cukup','Baik', 'Baik Sekali']

In [ ]:
data['tugas_binneed'] = pd.cut(data['nilai tugas'], bins=batas_bin, labels=
kategori)

In [ ]:
print(data)

        nim    nm_mhs     kelas  ...  nilai tugas keterangan  tugas_binneed
0  21042019      Rina  11.3B.05  ...           95        NaN    Baik Sekali
1  21042020       Uni  11.3B.06  ...           90        NaN    Baik Sekali
2  21042021      Diah  11.3B.07  ...           85        NaN           Baik
3  21042022     Ilham  11.3B.08  ...           95        NaN    Baik Sekali
4  21042023     Irwan  11.3B.09  ...          100        NaN    Baik Sekali
5  21042024     Ragil  11.3B.10  ...           70        NaN          Cukup
6  21042025     Andre  11.3B.11  ...           80        NaN           Baik
7  21042026  Muhammad  11.3B.12  ...           75        NaN          Cukup
8  21042027     Affan  11.3B.13  ...           85        NaN           Baik

[9 rows x 8 columns]

**Teknik Linspace**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/nilai.csv')
data.head(9)

        nim    nm_mhs     kelas  ...          nm_mtk nilai tugas  keterangan
0  21042019      Rina  11.3B.05  ...  DATA WAREHOUSE          95         NaN
1  21042020       Uni  11.3B.06  ...  DATA WAREHOUSE          90         NaN
2  21042021      Diah  11.3B.07  ...  DATA WAREHOUSE          85         NaN
3  21042022     Ilham  11.3B.08  ...  DATA WAREHOUSE          95         NaN
4  21042023     Irwan  11.3B.09  ...  DATA WAREHOUSE         100         NaN
5  21042024     Ragil  11.3B.10  ...  DATA WAREHOUSE          70         NaN
6  21042025     Andre  11.3B.11  ...  DATA WAREHOUSE          80         NaN
7  21042026  Muhammad  11.3B.12  ...  DATA WAREHOUSE          75         NaN
8  21042027     Affan  11.3B.13  ...  DATA WAREHOUSE          85         NaN

[9 rows x 7 columns]

In [ ]:
bins = np.linspace(min(data['nilai tugas']), max(data['nilai tugas']), 3)
print(bins)

[ 70.  85. 100.]

In [ ]:
kategori = ['Cukup','Baik', 'Baik Sekali']

In [ ]:
data['nilai_binned'] = pd.cut(data['nilai tugas'], bins=len(bins), labels=kategori, include_lowest=False)

In [ ]:
print (data)

        nim    nm_mhs     kelas  ...  nilai tugas keterangan  nilai_binned
0  21042019      Rina  11.3B.05  ...           95        NaN   Baik Sekali
1  21042020       Uni  11.3B.06  ...           90        NaN          Baik
2  21042021      Diah  11.3B.07  ...           85        NaN          Baik
3  21042022     Ilham  11.3B.08  ...           95        NaN   Baik Sekali
4  21042023     Irwan  11.3B.09  ...          100        NaN   Baik Sekali
5  21042024     Ragil  11.3B.10  ...           70        NaN         Cukup
6  21042025     Andre  11.3B.11  ...           80        NaN         Cukup
7  21042026  Muhammad  11.3B.12  ...           75        NaN         Cukup
8  21042027     Affan  11.3B.13  ...           85        NaN          Baik

[9 rows x 8 columns]

In [ ]:
data['nilai_binned'] = pd.cut(data['nilai tugas'], bins=len(bins), labels=kategori, include_lowest=True)

In [ ]:
print (data)

        nim    nm_mhs     kelas  ...  nilai tugas keterangan  nilai_binned
0  21042019      Rina  11.3B.05  ...           95        NaN   Baik Sekali
1  21042020       Uni  11.3B.06  ...           90        NaN          Baik
2  21042021      Diah  11.3B.07  ...           85        NaN          Baik
3  21042022     Ilham  11.3B.08  ...           95        NaN   Baik Sekali
4  21042023     Irwan  11.3B.09  ...          100        NaN   Baik Sekali
5  21042024     Ragil  11.3B.10  ...           70        NaN         Cukup
6  21042025     Andre  11.3B.11  ...           80        NaN         Cukup
7  21042026  Muhammad  11.3B.12  ...           75        NaN         Cukup
8  21042027     Affan  11.3B.13  ...           85        NaN          Baik

[9 rows x 8 columns]

**Teknik quantile**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/nilai.csv', sep=',')
data.head(9)

        nim    nm_mhs     kelas  ...          nm_mtk nilai tugas  keterangan
0  21042019      Rina  11.3B.05  ...  DATA WAREHOUSE          95         NaN
1  21042020       Uni  11.3B.06  ...  DATA WAREHOUSE          90         NaN
2  21042021      Diah  11.3B.07  ...  DATA WAREHOUSE          85         NaN
3  21042022     Ilham  11.3B.08  ...  DATA WAREHOUSE          95         NaN
4  21042023     Irwan  11.3B.09  ...  DATA WAREHOUSE         100         NaN
5  21042024     Ragil  11.3B.10  ...  DATA WAREHOUSE          70         NaN
6  21042025     Andre  11.3B.11  ...  DATA WAREHOUSE          80         NaN
7  21042026  Muhammad  11.3B.12  ...  DATA WAREHOUSE          75         NaN
8  21042027     Affan  11.3B.13  ...  DATA WAREHOUSE          85         NaN

[9 rows x 7 columns]

In [ ]:
data['nilai tugas_binned3'] = pd.qcut(data['nilai tugas'], 3)
print (data)

        nim    nm_mhs     kelas  ...  nilai tugas keterangan  nilai tugas_binned3
0  21042019      Rina  11.3B.05  ...           95        NaN      (91.667, 100.0]
1  21042020       Uni  11.3B.06  ...           90        NaN     (83.333, 91.667]
2  21042021      Diah  11.3B.07  ...           85        NaN     (83.333, 91.667]
3  21042022     Ilham  11.3B.08  ...           95        NaN      (91.667, 100.0]
4  21042023     Irwan  11.3B.09  ...          100        NaN      (91.667, 100.0]
5  21042024     Ragil  11.3B.10  ...           70        NaN     (69.999, 83.333]
6  21042025     Andre  11.3B.11  ...           80        NaN     (69.999, 83.333]
7  21042026  Muhammad  11.3B.12  ...           75        NaN     (69.999, 83.333]
8  21042027     Affan  11.3B.13  ...           85        NaN     (83.333, 91.667]

[9 rows x 8 columns]

In [ ]:
kategori = ['Cukup','Baik', 'Baik Sekali']
data['nilai tugas_binned3'] = pd.qcut(data['nilai tugas'], q=3, labels=kategori)
print (data)

        nim    nm_mhs     kelas  ...  nilai tugas keterangan  nilai tugas_binned3
0  21042019      Rina  11.3B.05  ...           95        NaN          Baik Sekali
1  21042020       Uni  11.3B.06  ...           90        NaN                 Baik
2  21042021      Diah  11.3B.07  ...           85        NaN                 Baik
3  21042022     Ilham  11.3B.08  ...           95        NaN          Baik Sekali
4  21042023     Irwan  11.3B.09  ...          100        NaN          Baik Sekali
5  21042024     Ragil  11.3B.10  ...           70        NaN                Cukup
6  21042025     Andre  11.3B.11  ...           80        NaN                Cukup
7  21042026  Muhammad  11.3B.12  ...           75        NaN                Cukup
8  21042027     Affan  11.3B.13  ...           85        NaN                 Baik

[9 rows x 8 columns]